### ISSUE TITLE
Stand Alone and Cloud One API Keys could be leaked

### ISSUE THREAD

**Issue by atiradocc** [atiradocc/conformity-migration-tool#19]
Make sure to remove the .csv file generated by the tool for AWS keys and the .yaml config files for Conformity API Keys from the local system after all the migration is done to prevent future leakage of the keys.

**Comment by felipecosta09** [comment]
I don't know if will be a good idea to remove after the migration, since it can be execute multiples times for several accounts. What we already have that is helpful is a task to clean the legacy account but not to delete the local files, since is easier to the user executing the tool to delete the files I don't know if there is too much value in the tool to do that...

Thoughts? @atiradocc @ronald-bautista

**Comment by ronald-bautista** [comment]
I was thinking about just printing a warning message at the end of each run of the tool that says something like 'The file user_config.yml contains your API Keys, don't forget to delete this after migration.'

**Comment by felipecosta09** [comment]
> I was thinking about just printing a warning message at the end of each run of the tool that says something like 'The file user_config.yml contains your API Keys, don't forget to delete this after migration.'

Make sense to me!

**Comment by fionagriffin-1** [comment]
Hi, did we have any update on this?

**Comment by felipecosta09** [comment]
It has been fixed on the release [v0.13.0](https://github.com/trendmicro/conformity-migration-tool/releases/tag/v0.13.0)
